// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck.Data;

namespace Truck.Data.Migrations
{
    [DbContext(typeof(TruckContext))]
    [Migration("20200718150942_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Truck.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Caminhão"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Carro"
                        });
                });

            modelBuilder.Entity("Truck.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Veiculo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Preco = 40000.0m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Preco = 45000.0m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Marca = "Nissan",
                            Modelo = "Versa",
                            Preco = 23000.0m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Marca = "Hyundai",
                            Modelo = "HR",
                            Preco = 70000.0m
                        });
                });

            modelBuilder.Entity("Truck.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Truck.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Veiculos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
